import http from 'k6/http';
import { check, sleep } from 'k6';

// Load the JSON payload generated by our Go script
const widePayload = open('./examples/bench_wide.json');

export const options = {
  // Ramp up to 50 concurrent users over 30 seconds
  stages: [
    { duration: '10s', target: 50 },
    { duration: '20s', target: 50 },
    { duration: '5s', target: 0 },
  ],
};

export default function () {
  const params = {
    headers: { 'Content-Type': 'application/json' },
  };

  // Blast the API
  const res = http.post('http://localhost:6969/submit', widePayload, params);

  // Verify the server accepted the DAG without crashing
  check(res, {
    'status is 202 Accepted': (r) => r.status === 202,
  });

  sleep(1); // Wait 1 second between submissions per virtual user
}